steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/aso-analyzer-pro-app/daily-tracking-worker', '-f', 'Dockerfile.job', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/aso-analyzer-pro-app/daily-tracking-worker']
images:
  - 'gcr.io/aso-analyzer-pro-app/daily-tracking-worker'
